from pathlib import Path
root=Path(__file__).resolve().parent
main=(root/'src/main.rs').read_text(); http=(root/'src/http.rs').read_text(); demo=(root/'demo/src/main.rs').read_text()
root_cargo=(root/'Cargo.toml').read_text(); demo_cargo=(root/'demo/Cargo.toml').read_text()
def need(c,m):
    if not c: raise SystemExit('FAIL: '+m)
need('version = "0.7.55"' in root_cargo,'root version')
need('version = "0.7.55"' in demo_cargo,'demo version')
need('#[arg(long, default_value_t = 1.0)]\n    gain: f32' in main,'--gain CLI')
need('--gain must be a finite value >= 0.0' in main,'gain validation')
need('OutputPeakGuard::process_all(result.sample_rate, &playback_samples, args.gain)' in main,'CLI gain protected after native DSP')
need('gain: Option<f32>' in http,'HTTP gain field')
need('default_gain: f32' in http,'server default gain')
need('req.gain.unwrap_or(state.default_gain)' in http,'HTTP gain resolution')
need('peak_guard.process(&processed, gain)' in http and 'pcm_bytes(&protected)' in http,'stream gain protected after native DSP')
need('OutputPeakGuard::process_all(48_000, &rendered_samples, gain)' in http and 'wav_bytes(&protected_samples)' in http,'WAV gain protected after native DSP')
need('const DEFAULT_GAIN_PERCENT: u32 = 100' in demo,'demo 100% default')
need('gain_percent: u32' in demo,'demo gain state')
need('"gain" => {' in demo,'settings gain parser')
need('gain={:.2}' in demo,'settings gain writer')
need('.with_label("Gain (%):")' in demo,'gain control')
need('.arg("--gain")' in demo,'demo passes gain to owned engine')
need('"gain": effective_gain' in demo and 'fn effective_gain(&self, base_gain: f32)' in demo,'demo request uses explicit effective gain')
need('DEMO_PLAYBACK_GAIN' not in demo,'fixed gain removed')
print('Gain setting validation passed.')
